name: deployBlog

on:
  push:
    branches:
      - 'main'

jobs:
  publish-blog:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Swift
      uses: slashmo/install-swift@v0.1.0
      with:
        version: 5.5

    - name: Build blog
      run: |
        swift run
        
    - name: Push
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: deploy
        FOLDER: ./Output
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE: "Build: ({sha}) {msg}"
