name: deployBlog

on:
  push:
    branches:
      - 'main'

jobs:
  publish-fund-app:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Swift
      uses: slashmo/install-swift@v0.1.0
      with:
        version: 5.5

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build blog
      run: |
        swift run
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: deploy
        destination_dir: '/build/Output'
    
